import { cp, mkdir, open, readFile, readdir, rename, rm, stat } from 'node:fs/promises'
import { dirname, join, resolve, sep } from 'node:path'
import { randomUUID } from 'node:crypto'
import { withoutLegacyExpansionSettings, type ProjectViewSettings } from '../domain/project.js'
import type { UserIdentity } from '../domain/task.js'
import { builtInThemes, type CustomTheme } from '../domain/theme.js'

export type GlobalTheme='mist'|'sage'|'ocean'|'rose'|'graphite'|'forest'|'coast'|'custom'
export interface LegacyCustomTheme {accent:string;scene:string;backgroundImage:string|null}
export interface LocalSettings {schema:'bearai.todo/settings@1';workspacePath:string|null;theme:GlobalTheme;sidebarWidth:number;customTheme:LegacyCustomTheme;customThemes:CustomTheme[];todayWindowDays:number;projectDefaults:ProjectViewSettings;currentUser?:UserIdentity;updatedAt:string}
async function atomicJson(path:string,value:unknown){await mkdir(dirname(path),{recursive:true});const temp=`${path}.${randomUUID()}.tmp`;const handle=await open(temp,'wx');try{await handle.writeFile(`${JSON.stringify(value,null,2)}\n`,'utf8');await handle.sync()}finally{await handle.close()}await rename(temp,path)}
export class SettingsRepository {
  constructor(private path:string){}
  async read():Promise<LocalSettings>{const defaults={schema:'bearai.todo/settings@1' as const,workspacePath:null,theme:'mist' as GlobalTheme,sidebarWidth:262,customTheme:{accent:'#4fa879',scene:'#e9f1ef',backgroundImage:null},customThemes:[] as CustomTheme[],todayWindowDays:3,projectDefaults:{sortMode:'manual',theme:'mist',defaultTaskExpansion:{mode:'collapsed',depth:'all'},rememberTaskExpansion:false,showSubprojects:false,expandedTaskIds:[]} as ProjectViewSettings,updatedAt:new Date().toISOString()};try{const value=JSON.parse(await readFile(this.path,'utf8')),legacy=value.projectDefaults??{},rawDepth=legacy.defaultTaskExpansion?.depth??legacy.rememberDefaultDepth??legacy.defaultTaskExpandDepth??legacy.expandDepth??'all',depth=rawDepth==='all'?'all':Math.max(1,Math.min(5,Number(rawDepth)||1)),mode=legacy.defaultTaskExpansion?.mode??(legacy.expandMode==='expanded'||(!legacy.expandMode&&legacy.defaultTaskExpandDepth>0)?'depth':'collapsed'),rememberTaskExpansion=legacy.rememberTaskExpansion??legacy.expandMode==='remember',current=withoutLegacyExpansionSettings(legacy),legacyCustom={...defaults.customTheme,...value.customTheme};let customThemes=Array.isArray(value.customThemes)?value.customThemes:[];if(!customThemes.length&&value.theme==='custom'){const now=value.updatedAt??new Date().toISOString();customThemes=[{id:'custom-migrated',name:'原自定义主题',tokens:{...builtInThemes.mist.tokens,scene:legacyCustom.scene,sceneLayer:legacyCustom.scene,accent:legacyCustom.accent},backgroundImage:legacyCustom.backgroundImage,createdAt:now,updatedAt:now}]}const theme=value.theme==='custom'&&customThemes[0]?customThemes[0].id:(value.theme??defaults.theme);return{...defaults,...value,theme,sidebarWidth:Math.min(380,Math.max(220,Number(value.sidebarWidth)||262)),customTheme:legacyCustom,customThemes,todayWindowDays:value.todayWindowDays===undefined?defaults.todayWindowDays:Math.min(30,Math.max(0,Math.trunc(Number(value.todayWindowDays)||0))),projectDefaults:{...defaults.projectDefaults,...current,defaultTaskExpansion:{mode,depth},rememberTaskExpansion}}}catch{return defaults}}
  async save(value:LocalSettings){await atomicJson(this.path,value);return value}
  async setWorkspace(workspacePath:string){const current=await this.read();return this.save({...current,workspacePath:resolve(workspacePath),updatedAt:new Date().toISOString()})}
  async setTheme(theme:GlobalTheme){const current=await this.read();return this.save({...current,theme,updatedAt:new Date().toISOString()})}
  async setPreferences(patch:Partial<Pick<LocalSettings,'theme'|'sidebarWidth'|'customTheme'|'customThemes'|'todayWindowDays'|'projectDefaults'|'currentUser'>>){const current=await this.read();return this.save({...current,...patch,sidebarWidth:patch.sidebarWidth===undefined?current.sidebarWidth:Math.min(380,Math.max(220,patch.sidebarWidth)),todayWindowDays:patch.todayWindowDays===undefined?current.todayWindowDays:Math.min(30,Math.max(0,Math.trunc(patch.todayWindowDays))),customTheme:patch.customTheme?{...current.customTheme,...patch.customTheme}:current.customTheme,customThemes:patch.customThemes??current.customThemes,projectDefaults:patch.projectDefaults?{...current.projectDefaults,...patch.projectDefaults}:current.projectDefaults,updatedAt:new Date().toISOString()})}
}
async function evidence(root:string){let projects=0,tasks=0;async function walk(directory:string){for(const entry of await readdir(directory,{withFileTypes:true})){const path=join(directory,entry.name);if(entry.isDirectory()){await walk(path);continue}if(entry.name==='.bearai-project.json')projects++;else if(entry.name.endsWith('.md'))tasks++}}await walk(root);return{projects,tasks}}
export async function migrateWorkspace(source:string,target:string){const from=resolve(source),to=resolve(target);if(from===to)return{...(await evidence(from)),source:from,target:to,sourceRemoved:false};if(to.startsWith(from+sep)||from.startsWith(to+sep))throw new Error('新旧工作目录不能互相嵌套');await mkdir(to,{recursive:true});if((await readdir(to)).length)throw new Error('新工作目录必须为空，避免覆盖已有文件');for(const entry of await readdir(from)){await cp(join(from,entry),join(to,entry),{recursive:true,errorOnExist:true,force:false})}const before=await evidence(from),after=await evidence(to);if(before.projects!==after.projects||before.tasks!==after.tasks)throw new Error('工作目录迁移校验失败');await stat(join(to,'.bearai-workspace.json'));await rm(from,{recursive:true,force:false});return{...after,source:from,target:to,sourceRemoved:true}}
