import { mkdir, open, readFile, rename, stat } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { randomUUID } from 'node:crypto'
import type { UserIdentity } from '../domain/task.js'
import { WorkspaceRepository } from './workspaceRepository.js'

export interface WorkspaceRegistration {workspaceId:string;name:string;path:string;createdAt:string;lastOpenedAt:string}
export interface WorkspaceRegistry {schema:'bearai.todo/workspace-registry@1';revision:number;activeWorkspaceId:string|null;user:UserIdentity;workspaces:WorkspaceRegistration[];updatedAt:string}
const defaultUser:UserIdentity={id:'local-self',name:'本地用户',email:''}
async function atomicJson(path:string,value:unknown){await mkdir(dirname(path),{recursive:true});const temp=`${path}.${randomUUID()}.tmp`,handle=await open(temp,'wx');try{await handle.writeFile(`${JSON.stringify(value,null,2)}\n`,'utf8');await handle.sync()}finally{await handle.close()}await rename(temp,path)}
export class WorkspaceRegistryRepository{
  constructor(private readonly path:string){}
  async read():Promise<WorkspaceRegistry>{try{const value=JSON.parse(await readFile(this.path,'utf8'));return{schema:'bearai.todo/workspace-registry@1',revision:Number(value.revision)||1,activeWorkspaceId:value.activeWorkspaceId??null,user:{...defaultUser,...value.user},workspaces:Array.isArray(value.workspaces)?value.workspaces.map((item:WorkspaceRegistration)=>({...item,path:resolve(item.path)})):[],updatedAt:value.updatedAt??new Date().toISOString()}}catch{return{schema:'bearai.todo/workspace-registry@1',revision:1,activeWorkspaceId:null,user:defaultUser,workspaces:[],updatedAt:new Date().toISOString()}}}
  private async save(value:WorkspaceRegistry){await atomicJson(this.path,value);return value}
  async ensure(initialPath:string){let registry=await this.read();if(!registry.workspaces.length)registry=await this.add(initialPath,true);return registry}
  async add(path:string,activate=false){const root=resolve(path),workspace=await new WorkspaceRepository(root).initialize();let registry=await this.read(),existing=registry.workspaces.find(item=>item.workspaceId===workspace.workspaceId||item.path.toLocaleLowerCase()===root.toLocaleLowerCase()),now=new Date().toISOString();if(existing){if(activate)return this.save({...registry,activeWorkspaceId:existing.workspaceId,revision:registry.revision+1,updatedAt:now});return registry}const item:WorkspaceRegistration={workspaceId:workspace.workspaceId,name:workspace.name,path:root,createdAt:workspace.createdAt,lastOpenedAt:now};registry={...registry,revision:registry.revision+1,activeWorkspaceId:activate||!registry.activeWorkspaceId?item.workspaceId:registry.activeWorkspaceId,workspaces:[...registry.workspaces,item],updatedAt:now};return this.save(registry)}
  async activate(workspaceId:string){const registry=await this.read(),target=registry.workspaces.find(item=>item.workspaceId===workspaceId);if(!target)throw new Error('工作区未注册');await stat(join(target.path,'.bearai-workspace.json'));const now=new Date().toISOString();return this.save({...registry,revision:registry.revision+1,activeWorkspaceId:workspaceId,workspaces:registry.workspaces.map(item=>item.workspaceId===workspaceId?{...item,lastOpenedAt:now}:item),updatedAt:now})}
  async remove(workspaceId:string){const registry=await this.read();if(registry.workspaces.length<=1)throw new Error('至少保留一个工作区');const workspaces=registry.workspaces.filter(item=>item.workspaceId!==workspaceId);if(workspaces.length===registry.workspaces.length)throw new Error('工作区未注册');return this.save({...registry,revision:registry.revision+1,activeWorkspaceId:registry.activeWorkspaceId===workspaceId?workspaces[0].workspaceId:registry.activeWorkspaceId,workspaces,updatedAt:new Date().toISOString()})}
  async rename(workspaceId:string,name:string){const normalized=name.trim();if(!normalized)throw new Error('工作区名称不能为空');const registry=await this.read(),item=registry.workspaces.find(value=>value.workspaceId===workspaceId);if(!item)throw new Error('工作区未注册');const workspaceRepository=new WorkspaceRepository(item.path),workspace=await workspaceRepository.read(),now=new Date().toISOString();await workspaceRepository.save({...workspace,name:normalized,revision:workspace.revision+1,updatedAt:now});return this.save({...registry,revision:registry.revision+1,workspaces:registry.workspaces.map(value=>value.workspaceId===workspaceId?{...value,name:normalized}:value),updatedAt:now})}
  async updatePath(workspaceId:string,path:string){const registry=await this.read();if(!registry.workspaces.some(item=>item.workspaceId===workspaceId))throw new Error('工作区未注册');return this.save({...registry,revision:registry.revision+1,workspaces:registry.workspaces.map(item=>item.workspaceId===workspaceId?{...item,path:resolve(path)}:item),updatedAt:new Date().toISOString()})}
  async setUser(user:UserIdentity){const registry=await this.read();return this.save({...registry,revision:registry.revision+1,user:{...defaultUser,...user},updatedAt:new Date().toISOString()})}
}
