import type { Task } from './task.js'
export type SmartViewId='today'|'favorites'|'planned'|'completed'
export type DueState='outside'|'upcoming'|'today'|'overdue'
const DATE_ONLY=/^\d{4}-\d{2}-\d{2}$/
function dayStart(value:Date){return new Date(value.getFullYear(),value.getMonth(),value.getDate())}
function calendarDay(value:string){const match=/^(\d{4})-(\d{2})-(\d{2})/.exec(value);return match?new Date(Number(match[1]),Number(match[2])-1,Number(match[3])):null}
export function dueState(due:string,windowDays:number,now=new Date()):DueState{const today=dayStart(now),dueDay=calendarDay(due);if(!dueDay||Number.isNaN(dueDay.getTime()))return'outside';if(dueDay<today)return'overdue';if(dueDay.getTime()===today.getTime()){if(!DATE_ONLY.test(due)&&new Date(due).getTime()<now.getTime())return'overdue';return'today'}const boundary=new Date(today);boundary.setDate(boundary.getDate()+Math.max(0,windowDays));return dueDay<=boundary?'upcoming':'outside'}
export function queryTasks(tasks:Task[],view:SmartViewId|string,options:{todayWindowDays?:number;now?:Date}={}){return tasks.filter(task=>{if(task.parentId)return false;if(view==='today')return task.status==='active'&&Boolean(task.due)&&dueState(task.due!,options.todayWindowDays??3,options.now)!=='outside';if(view==='favorites')return task.status==='active'&&task.favorite;if(view==='planned')return task.status==='active'&&Boolean(task.due);if(view==='completed')return task.status==='completed';return task.status==='active'&&task.projectId===view}).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
export function childTasks(tasks:Task[],parentId:string){return tasks.filter(task=>task.parentId===parentId).sort((a,b)=>(a.order??Number.MAX_SAFE_INTEGER)-(b.order??Number.MAX_SAFE_INTEGER)||a.createdAt.localeCompare(b.createdAt))}
export function partitionChildTasks(tasks:Task[],parentId:string){const children=childTasks(tasks,parentId);return{active:children.filter(task=>task.status!=='completed'),completed:children.filter(task=>task.status==='completed')}}
export function completedProjectTasks(tasks:Task[],projectId:string,term=''){const query=term.trim().toLocaleLowerCase();return tasks.filter(task=>task.projectId===projectId&&task.status==='completed'&&!task.parentId).filter(task=>!query||[task.title,task.note,...task.tags].some(value=>value.toLocaleLowerCase().includes(query))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
