export const builtInThemeIds = ['mist','sage','ocean','rose','graphite','forest','coast'] as const
export type BuiltInThemeId = typeof builtInThemeIds[number]
export interface ThemeTokens {scene:string;sceneLayer:string;panel:string;card:string;hover:string;accent:string;accentAlt:string;text:string;muted:string;border:string;danger:string;shadow:string}
export interface CustomTheme {id:string;name:string;tokens:ThemeTokens;backgroundImage:string|null;createdAt:string;updatedAt:string}
export const builtInThemes:Record<BuiltInThemeId,{name:string;image?:'forest'|'coast';tokens:ThemeTokens}>={
mist:{name:'晨雾',tokens:{scene:'#e8f0f2',sceneLayer:'#cbdde2',panel:'#f8fbfc',card:'#ffffff',hover:'#d9e7ea',accent:'#376f7b',accentAlt:'#8b6f47',text:'#15282d',muted:'#526c72',border:'#a9c0c6',danger:'#a53f42',shadow:'#26434a'}},sage:{name:'青苔',tokens:{scene:'#e6eee5',sceneLayer:'#c5d8c2',panel:'#f7faf5',card:'#fffef9',hover:'#d7e5d2',accent:'#397044',accentAlt:'#8a672f',text:'#172719',muted:'#566a58',border:'#adc1aa',danger:'#a13e3e',shadow:'#29432d'}},ocean:{name:'海湾',tokens:{scene:'#e4edf7',sceneLayer:'#bfd1e8',panel:'#f7faff',card:'#ffffff',hover:'#d3e2f4',accent:'#315f9b',accentAlt:'#217f83',text:'#15243a',muted:'#536a87',border:'#a8bdd9',danger:'#ad3e52',shadow:'#223d64'}},rose:{name:'晚樱',tokens:{scene:'#f7e8ec',sceneLayer:'#edc3ce',panel:'#fff8fa',card:'#fffdfd',hover:'#f4d5de',accent:'#9b3f5a',accentAlt:'#7c5a99',text:'#341a22',muted:'#805c67',border:'#d9aeb9',danger:'#a72d37',shadow:'#6b2d3f'}},graphite:{name:'墨石',tokens:{scene:'#252b31',sceneLayer:'#39424b',panel:'#303840',card:'#3a434c',hover:'#46535e',accent:'#78b6cf',accentAlt:'#d4a75c',text:'#f3f6f8',muted:'#b6c0c8',border:'#596672',danger:'#ff7b7b',shadow:'#090c0f'}},forest:{name:'林间',image:'forest',tokens:{scene:'#dce9df',sceneLayer:'#8eb09a',panel:'#f3f8f3',card:'#fbfdf8',hover:'#ccdfd0',accent:'#275e3e',accentAlt:'#a36d2f',text:'#14251a',muted:'#526959',border:'#9fb8a5',danger:'#a43d3d',shadow:'#1d3b29'}},coast:{name:'海岸',image:'coast',tokens:{scene:'#dceef0',sceneLayer:'#87bac3',panel:'#f4fbfb',card:'#fffefb',hover:'#cbe4e8',accent:'#236d7c',accentAlt:'#c17242',text:'#122b31',muted:'#4d6f76',border:'#99c0c7',danger:'#a94343',shadow:'#17414a'}}}
export function isBuiltInTheme(value:string):value is BuiltInThemeId{return builtInThemeIds.includes(value as BuiltInThemeId)}
export function themeTokens(id:string,customThemes:CustomTheme[]=[]):ThemeTokens{return isBuiltInTheme(id)?builtInThemes[id].tokens:customThemes.find(theme=>theme.id===id)?.tokens??builtInThemes.mist.tokens}
export function resolveThemeId(settingsOpen:boolean,transientPreview:string|null,projectOverride:string|null,globalTheme:string){return settingsOpen&&transientPreview?transientPreview:(projectOverride??globalTheme)}
