import { afterEach, describe, expect, it } from 'vitest'
import { mkdtemp, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'; import { tmpdir } from 'node:os'
import { TaskRepository } from '../src/infrastructure/taskRepository'; import { parseTask, serializeTask } from '../src/infrastructure/taskCodec'
import { ProjectRepository } from '../src/infrastructure/workspaceRepository'
const roots:string[]=[]; async function repo(){const root=await mkdtemp(join(tmpdir(),'bear-todo-'));roots.push(root);return{root,repository:new TaskRepository(root)}}
afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true})))})
describe('Markdown task repository',()=>{
  it('creates a readable task file inside the default project folder',async()=>{const{root,repository}=await repo();const task=await repository.create('第一件事');const files=await import('node:fs/promises').then(fs=>fs.readdir(join(root,'默认项目')));const text=await readFile(join(root,'默认项目',files.find(name=>name.endsWith('.md'))!),'utf8');expect(text).toContain('bearai.todo/task@2');expect(parseTask(text).title).toBe('第一件事');expect(task.projectId).toBeTruthy()})
  it('lists tasks and persists a revisioned favorite update',async()=>{const{repository}=await repo();const first=await repository.create('第一件事');const second=await repository.create('第二件事');const saved=await repository.save({...first,favorite:true},1);expect(saved.revision).toBe(2);expect((await repository.get(first.id)).favorite).toBe(true);expect((await repository.list()).map(task=>task.id)).toContain(second.id)})
  it('persists a child task as its own Markdown file',async()=>{const{repository}=await repo();const parent=await repository.create('父任务');const child=await repository.create('子任务',parent.projectId,parent.id);expect(child.parentId).toBe(parent.id);expect((await repository.list()).filter(task=>task.parentId===parent.id)).toHaveLength(1)})
  it('treats the containing project folder as authority after an external move',async()=>{const{root,repository}=await repo();const source=await repository.create('可移动任务');const projects=new ProjectRepository(root),target=await projects.create('目标项目',null);const file=(await readdir(join(root,'默认项目'))).find(name=>name.endsWith('.md'))!;await rename(join(root,'默认项目',file),join(root,target.relativePath,file));expect((await repository.get(source.id)).projectId).toBe(target.projectId)})
  it('preserves legacy and unknown frontmatter during v2 reads',()=>{const task=parseTask('---\nschema: bearai.todo/task@1\nid: abc\nrevision: 1\ntitle: T\nlistId: inbox\nstatus: active\nimportant: true\ncreatedAt: now\nupdatedAt: now\npluginValue:\n  nested: 42\n---\n原始正文\n');const round=parseTask(serializeTask(task));expect(round.favorite).toBe(true);expect(round.extra.pluginValue).toEqual({nested:42});expect(round.note).toBe('原始正文\n')})
  it('rejects stale saves after an external edit',async()=>{const{root,repository}=await repo();const task=await repository.create('原任务');const files=await import('node:fs/promises').then(fs=>fs.readdir(join(root,'默认项目'))),path=join(root,'默认项目',files.find(name=>name.endsWith('.md'))!);const external={...task,revision:2,title:'外部修改'};await writeFile(path,serializeTask(external),'utf8');await expect(repository.save({...task,title:'应用修改'},1)).rejects.toThrow('外部修改');expect((await repository.get(task.id)).title).toBe('外部修改')})
})
