import { describe, expect, it } from 'vitest'
import type { Task } from '../src/domain/task'
import { activeProjectTreeTaskCount, childTasks, completedProjectTasks, voidedProjectTasks, dueState, partitionChildTasks, queryTasks } from '../src/domain/taskQueries'
import { nextRepeatDue, nextRecurringTask } from '../src/domain/taskRecurrence'
function task(patch:Partial<Task>={}):Task{return{schema:'bearai.todo/task@2',id:crypto.randomUUID(),revision:1,title:'任务',projectId:'project-a',parentId:null,status:'active',favorite:false,tags:[],attachments:[],createdAt:'2026-08-05T00:00:00Z',updatedAt:'2026-08-05T00:00:00Z',note:'',extra:{},...patch}}
describe('smart task queries',()=>{
  const values=[task({id:'plain'}),task({id:'star',favorite:true}),task({id:'due',due:'2026-08-10'}),task({id:'done',status:'completed'}),task({id:'custom',projectId:'project-b'})]
  it('defines Today as incomplete due tasks inside the local calendar window',()=>{expect(queryTasks(values,'today',{todayWindowDays:3,now:new Date('2026-08-08T12:00:00')}).map(x=>x.id)).toEqual(['due'])})
  it('queries favorites, planned, completed and projects',()=>{expect(queryTasks(values,'favorites').map(x=>x.id)).toEqual(['star']);expect(queryTasks(values,'planned').map(x=>x.id)).toEqual(['due']);expect(queryTasks(values,'completed').map(x=>x.id)).toEqual(['done']);expect(queryTasks(values,'project-b').map(x=>x.id)).toEqual(['custom'])})
})
describe('child tasks',()=>{
  it('keeps child tasks out of top-level views and returns them under the parent',()=>{const parent=task({id:'parent',due:'2026-08-09'}),child=task({id:'child',parentId:'parent',due:'2026-08-09'});expect(queryTasks([parent,child],'today',{now:new Date('2026-08-08T12:00:00')}).map(value=>value.id)).toEqual(['parent']);expect(childTasks([parent,child],'parent').map(value=>value.id)).toEqual(['child'])})
  it('classifies date-only and timed deadlines by local calendar day',()=>{const now=new Date(2026,11,31,12);expect(dueState('2026-12-31',3,now)).toBe('today');expect(dueState('2026-12-31T09:00:00+08:00',3,now)).toBe('overdue');expect(dueState('2027-01-03',3,now)).toBe('upcoming');expect(dueState('2027-01-04',3,now)).toBe('outside')})
  it('supports zero and one day windows without elapsed-hour math',()=>{const now=new Date(2026,7,8,23,50);expect(dueState('2026-08-09',0,now)).toBe('outside');expect(dueState('2026-08-09',1,now)).toBe('upcoming')})
  it('does not cascade parent completion to children',()=>{const child=task({id:'child',parentId:'parent'}),completedParent=task({id:'parent',status:'completed'});expect(childTasks([completedParent,child],'parent')[0].status).toBe('active')})
  it('places completed children in a separate group after active siblings',()=>{const active=task({id:'active-child',parentId:'parent',order:2}),completed=task({id:'done-child',parentId:'parent',order:1,status:'completed'}),groups=partitionChildTasks([active,completed],'parent');expect(groups.active.map(value=>value.id)).toEqual(['active-child']);expect(groups.completed.map(value=>value.id)).toEqual(['done-child'])})
  it('partitions voided children separately from active and completed siblings',()=>{const groups=partitionChildTasks([task({id:'active',parentId:'parent'}),task({id:'done',parentId:'parent',status:'completed'}),task({id:'void',parentId:'parent',status:'voided'})],'parent');expect(groups.active.map(x=>x.id)).toEqual(['active']);expect(groups.completed.map(x=>x.id)).toEqual(['done']);expect(groups.voided.map(x=>x.id)).toEqual(['void'])})
})
describe('completed project section',()=>{
  it('returns only completed top-level tasks from the current project',()=>{const values=[task({id:'done-a',status:'completed'}),task({id:'active'}),task({id:'other',projectId:'project-b',status:'completed'}),task({id:'child',parentId:'done-a',status:'completed'})];expect(completedProjectTasks(values,'project-a').map(value=>value.id)).toEqual(['done-a'])})
  it('filters completed tasks by title, note or tag',()=>{const values=[task({id:'title',title:'发布版本',status:'completed'}),task({id:'note',note:'包含验收证据',status:'completed'}),task({id:'tag',tags:['客户'],status:'completed'})];expect(completedProjectTasks(values,'project-a','验收').map(value=>value.id)).toEqual(['note']);expect(completedProjectTasks(values,'project-a','客户').map(value=>value.id)).toEqual(['tag'])})
  it('counts active tasks from the project and every descendant as one total',()=>{const projects:any[]=[{projectId:'root',parentId:null},{projectId:'child',parentId:'root'},{projectId:'grandchild',parentId:'child'},{projectId:'other',parentId:null}],values=[task({projectId:'child'}),task({projectId:'grandchild'}),task({projectId:'grandchild'}),task({projectId:'root',status:'completed'}),task({projectId:'other'})];expect(activeProjectTreeTaskCount(values,projects,'root')).toBe(3);expect(activeProjectTreeTaskCount(values,projects,'child')).toBe(3)})
  it('keeps voided tasks searchable in all while excluding them from active views and counts',()=>{const values=[task({id:'void',status:'voided',due:'2026-08-09',favorite:true}),task({id:'active'})];expect(queryTasks(values,'all').map(x=>x.id)).toContain('void');expect(queryTasks(values,'today',{now:new Date('2026-08-09T10:00:00')}).map(x=>x.id)).not.toContain('void');expect(voidedProjectTasks(values,'project-a').map(x=>x.id)).toEqual(['void']);expect(activeProjectTreeTaskCount(values,[],'project-a')).toBe(1)})
  it('advances date-only repeat points and clamps month ends',()=>{expect(nextRepeatDue({frequency:'daily',interval:1},'2026-08-09')).toBe('2026-08-10');expect(nextRepeatDue({frequency:'weekly',interval:2},'2026-08-09')).toBe('2026-08-23');expect(nextRepeatDue({frequency:'monthly',interval:1},'2026-01-31')).toBe('2026-02-28');expect(nextRepeatDue({frequency:'yearly',interval:1},'2024-02-29')).toBe('2025-02-28')})
  it('creates a new active occurrence without sharing attachments or reminder',()=>{const source=task({id:'old',title:'每周复盘',due:'2026-08-09',reminder:'2026-08-09T09:00:00.000Z',repeat:{frequency:'weekly',interval:1},attachments:[{id:'a',name:'a.txt',relativePath:'.attachments/old/a.txt',mime:'text/plain',size:1,createdAt:'2026-08-01T00:00:00Z'}],note:'保留模板正文'}),next=nextRecurringTask(source,'new',new Date('2026-08-09T10:00:00Z'));expect(next).toMatchObject({id:'new',status:'active',due:'2026-08-16',reminder:null,completedAt:null,note:'保留模板正文',attachments:[]});expect(source.id).toBe('old')})
})
