import {afterEach,describe,expect,it} from 'vitest'
import {execFile,spawn} from 'node:child_process'
import {mkdtemp,readFile,readdir,rm,writeFile} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {pathToFileURL} from 'node:url'
import {promisify} from 'node:util'
import {ProjectRepository} from '../src/infrastructure/workspaceRepository'
import {TaskRepository} from '../src/infrastructure/taskRepository'
import {withWorkspaceWriteLock} from '../src/infrastructure/workspaceWriteLock'
import {executeAutomation} from '../cli/taskAutomation'

const exec=promisify(execFile),roots:string[]=[]
async function workspace(){const root=await mkdtemp(join(tmpdir(),'bear-cli-'));roots.push(root);const projects=await new ProjectRepository(root).initialize();return{root,projectId:projects[0].projectId}}
function cli(input:unknown){return new Promise<{code:number|null;stdout:string;stderr:string;json:any}>((resolve,reject)=>{const child=spawn(process.execPath,['dist-cli/cli/taskAutomation.js'],{cwd:process.cwd(),stdio:['pipe','pipe','pipe']}),out:string[]=[],err:string[]=[];child.stdout.on('data',chunk=>out.push(String(chunk)));child.stderr.on('data',chunk=>err.push(String(chunk)));child.on('error',reject);child.on('close',code=>{const stdout=out.join('');resolve({code,stdout,stderr:err.join(''),json:JSON.parse(stdout)})});child.stdin.end(JSON.stringify(input))})}
function ensure(root:string,projectId:string,key='brief:2026-08-09'){return{version:1,command:'ensure-instance',workspacePath:root,instance:{title:'每日实例',projectId,instanceKey:key,validOn:'2026-08-09',rollover:'forbidden'}}}

afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true})))})

describe('headless task automation CLI',()=>{
  it('reports stable capabilities and rejects a relative workspace with JSON-only stdout',async()=>{const {root}=await workspace(),cap=await cli({version:1,command:'capabilities',workspacePath:root}),bad=await cli({version:1,command:'capabilities',workspacePath:'relative'});expect(cap.code).toBe(0);expect(cap.stderr).toBe('');expect(cap.stdout.trim().split('\n')).toHaveLength(1);expect(cap.json.capabilities.workspaceLock).toBe('bearai-write-lock@1');expect(bad.code).toBe(2);expect(bad.json.error.code).toBe('INVALID_INPUT')})

  it('makes two concurrent CLI retries create one complete Markdown instance',async()=>{const {root,projectId}=await workspace(),[a,b]=await Promise.all([cli(ensure(root,projectId)),cli(ensure(root,projectId))]),tasks=await new TaskRepository(root).list();expect([a.json.receipts[0].action,b.json.receipts[0].action].sort()).toEqual(['created','existing']);expect(tasks.filter(task=>task.instanceKey==='brief:2026-08-09')).toHaveLength(1);expect(tasks[0]).toMatchObject({validOn:'2026-08-09',rollover:'forbidden',revision:1})})

  it('waits for an application-held lock instead of overwriting it',async()=>{const {root,projectId}=await workspace();let entered!:()=>void;const started=new Promise<void>(resolve=>{entered=resolve}),holding=withWorkspaceWriteLock(root,async()=>{entered();await new Promise(resolve=>setTimeout(resolve,250))});await started;const began=Date.now(),result=await cli({...ensure(root,projectId),lockTimeoutMs:2000});await holding;expect(result.code).toBe(0);expect(Date.now()-began).toBeGreaterThanOrEqual(180);expect(result.json.receipts[0].action).toBe('created')})

  it('returns a retryable lock timeout without leaving a half instance',async()=>{const {root,projectId}=await workspace();let entered!:()=>void;const started=new Promise<void>(resolve=>{entered=resolve}),holding=withWorkspaceWriteLock(root,async()=>{entered();await new Promise(resolve=>setTimeout(resolve,350))});await started;const failed=await cli({...ensure(root,projectId,'timeout-instance'),lockTimeoutMs:100});expect(failed.code).toBe(3);expect(failed.json.error).toMatchObject({code:'LOCK_TIMEOUT',retryable:true});expect((await new TaskRepository(root).findInstance('timeout-instance'))).toBeNull();await holding;const retried=await cli(ensure(root,projectId,'timeout-instance'));expect(retried.json.receipts[0].action).toBe('created');expect((await new TaskRepository(root).list()).filter(task=>task.instanceKey==='timeout-instance')).toHaveLength(1)})

  it('recovers a lock left by an abnormally exited process',async()=>{const {root,projectId}=await workspace(),moduleUrl=pathToFileURL(join(process.cwd(),'dist-cli/src/infrastructure/workspaceWriteLock.js')).href,script=`import {withWorkspaceWriteLock} from ${JSON.stringify(moduleUrl)}; await withWorkspaceWriteLock(${JSON.stringify(root)},async()=>process.exit(9));`;await exec(process.execPath,['--input-type=module','-e',script]).catch(()=>undefined);expect(await readdir(root)).toContain('.bearai-write.lock');const result=await cli(ensure(root,projectId,'after-crash'));expect(result.code).toBe(0);expect(await readdir(root)).not.toContain('.bearai-write.lock')})

  it('finds instances, voids expired tasks idempotently, and reads back receipts',async()=>{const {root,projectId}=await workspace();await cli({...ensure(root,projectId,'expired'),instance:{...ensure(root,projectId).instance,instanceKey:'expired',validOn:'2026-08-08'}});const first=await cli({version:1,command:'void-expired',workspacePath:root,today:'2026-08-09',reason:'自动化过期'}),second=await cli({version:1,command:'void-expired',workspacePath:root,today:'2026-08-09'}),found=await cli({version:1,command:'find-instance',workspacePath:root,instanceKey:'expired'});expect(first.json.receipts).toHaveLength(1);expect(first.json.receipts[0]).toMatchObject({action:'voided',previousStatus:'active',newStatus:'voided',reason:'自动化过期'});expect(second.json.receipts).toHaveLength(0);expect(found.json.receipts[0]).toMatchObject({action:'found',newStatus:'voided',revision:2})})

  it('reports per-task partial failure and preserves a concurrently revised task',async()=>{const {root,projectId}=await workspace(),created=await new TaskRepository(root).ensureInstance({title:'冲突实例',projectId,instanceKey:'conflict-instance',validOn:'2026-08-08',rollover:'forbidden'}),result:any=await executeAutomation({version:1,command:'void-expired',workspacePath:root,today:'2026-08-09'},{beforeVoid:async task=>{const repository=new TaskRepository(root);await repository.save({...task,note:'人工修改'},task.revision)}});expect(result).toMatchObject({ok:false,partial:true,receipts:[]});expect(result.errors).toHaveLength(1);const readback=await new TaskRepository(root).get(created.task.id);expect(readback).toMatchObject({status:'active',revision:2});expect(readback.note.trim()).toBe('人工修改')})

  it('keeps a legacy task@2 readable while creating a new instance',async()=>{const {root,projectId}=await workspace(),project=(await new ProjectRepository(root).list())[0],legacy=`---\nschema: bearai.todo/task@2\nid: legacy-task\nrevision: 1\ntitle: 旧任务\nprojectId: ${projectId}\nstatus: active\nfavorite: false\ntags: []\nattachments: []\ncreatedAt: '2026-01-01T00:00:00.000Z'\nupdatedAt: '2026-01-01T00:00:00.000Z'\n---\n旧正文\n`;await writeFile(join(root,project.relativePath,'legacy.md'),legacy,'utf8');expect((await cli(ensure(root,projectId,'new-instance'))).code).toBe(0);const tasks=await new TaskRepository(root).list();expect(tasks.find(task=>task.id==='legacy-task')?.note).toBe('旧正文\n');expect(tasks.filter(task=>task.instanceKey==='new-instance')).toHaveLength(1);expect(await readFile(join(root,project.relativePath,'legacy.md'),'utf8')).toBe(legacy)})
})
