import { app, BrowserWindow, dialog, ipcMain, Notification } from 'electron'
import { basename, extname, join, relative, resolve } from 'node:path'
import { copyFile, mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { randomUUID } from 'node:crypto'
import type { TaskAttachment } from '../src/domain/task.js'
import { TaskRepository } from '../src/infrastructure/taskRepository.js'
import { ProjectRepository, WorkspaceRepository } from '../src/infrastructure/workspaceRepository.js'
import { migrateWorkspace, SettingsRepository } from '../src/infrastructure/settingsRepository.js'
if(process.argv.includes('--smoke'))app.disableHardwareAcceleration()
let dataRoot=''
let repository:TaskRepository,projectRepository:ProjectRepository,workspaceRepository:WorkspaceRepository,settingsRepository:SettingsRepository
const reminderTimers=new Map<string,ReturnType<typeof setTimeout>>()
function configureRepositories(root:string){dataRoot=root;repository=new TaskRepository(root);projectRepository=new ProjectRepository(root);workspaceRepository=new WorkspaceRepository(root)}
const mimeTypes:Record<string,string>={'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.webp':'image/webp','.svg':'image/svg+xml','.pdf':'application/pdf','.txt':'text/plain','.md':'text/markdown','.json':'application/json','.csv':'text/csv','.mp3':'audio/mpeg','.wav':'audio/wav','.mp4':'video/mp4','.webm':'video/webm'}
function attachmentPath(value:string){const root=resolve(dataRoot,'.attachments'),target=resolve(dataRoot,value);if(target!==root&&!target.startsWith(root+'\\'))throw new Error('附件路径越界');return target}
function scheduleReminder(task:{id:string;title:string;reminder?:string|null;status:string}){const previous=reminderTimers.get(task.id);if(previous)clearTimeout(previous);reminderTimers.delete(task.id);if(!task.reminder||task.status==='completed')return;const delay=new Date(task.reminder).getTime()-Date.now();if(delay<=0||delay>2_147_000_000)return;reminderTimers.set(task.id,setTimeout(()=>{if(Notification.isSupported())new Notification({title:'熊智ToDo 提醒',body:task.title}).show();reminderTimers.delete(task.id)},delay))}
function createWindow() {
  const win = new BrowserWindow({ width: 1280, height: 800, minWidth: 760, minHeight: 560, frame:false, titleBarStyle:'hidden', backgroundColor:'#f3f2f1', webPreferences:{ preload:join(app.getAppPath(),'electron','preload.cjs'), contextIsolation:true, nodeIntegration:false, sandbox:true } })
  if (process.argv.includes('--dev')) void win.loadURL('http://localhost:5173')
  else void win.loadFile(join(import.meta.dirname,'../../dist/index.html'))
  if (process.argv.includes('--smoke')) win.webContents.once('did-finish-load', async () => {
    try {
      const result=await win.webContents.executeJavaScript(`(async()=>{const api=window.bearTodo;if(!api)throw new Error('bridge missing');const health=await api.health();const project=await api.createProject('冒烟项目',null);const childProject=await api.createProject('冒烟子项目',project.projectId);const task=await api.createTask('冒烟任务',project.projectId);const child=await api.createTask('冒烟子任务',project.projectId,task.id);const [projects,tasks]=await Promise.all([api.listProjects(),api.listTasks()]);return{health,projectPersisted:projects.some(x=>x.projectId===project.projectId),childProjectPersisted:projects.some(x=>x.projectId===childProject.projectId&&x.parentId===project.projectId),taskPersisted:tasks.some(x=>x.id===task.id&&x.projectId===project.projectId),childPersisted:tasks.some(x=>x.id===child.id&&x.parentId===task.id)}})()`)
      await new Promise(resolve=>setTimeout(resolve,500))
      if(process.env.BEARAI_SMOKE_INITIAL_SCREENSHOT)await writeFile(process.env.BEARAI_SMOKE_INITIAL_SCREENSHOT,(await win.webContents.capturePage()).toPNG())
      const layoutResult=await win.webContents.executeJavaScript(`(()=>{const shell=document.querySelector('.shell').getBoundingClientRect(),nav=document.querySelector('.nav').getBoundingClientRect(),list=document.querySelector('.list').getBoundingClientRect();return{viewport:{width:innerWidth,height:innerHeight},shell:{width:shell.width,height:shell.height},nav:{top:nav.top,bottom:nav.bottom,height:nav.height},list:{left:list.left,right:list.right,width:list.width},bodyScroll:{width:document.body.scrollWidth,height:document.body.scrollHeight}}})()`)
      Object.assign(result,{layoutResult,detailInitiallyHidden:await win.webContents.executeJavaScript(`!document.querySelector('.detail')`)})
      if(process.env.BEARAI_SMOKE_DETAIL_SCREENSHOT){await win.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms)),input=document.querySelector('.add input'),setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(input,'界面布局检查任务');input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new KeyboardEvent('keyup',{bubbles:true,key:'Enter'}));await wait(300);[...document.querySelectorAll('.task-kind button')].find(x=>x.textContent.includes('高级任务'))?.click();await wait(450)})()`);await writeFile(process.env.BEARAI_SMOKE_DETAIL_SCREENSHOT,(await win.webContents.capturePage()).toPNG())}
      const uiResult=await win.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms)),setInput=(input,value)=>{const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}))};let row=document.querySelector('.list-row');row.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:250,clientY:300}));await wait(100);[...document.querySelectorAll('.context-menu button')].find(x=>x.textContent.includes('新增子项目')).click();await wait(100);let input=document.querySelector('.modal>input');const subprojectDialogVisible=!!input;setInput(input,'界面子项目');document.querySelector('.modal').requestSubmit();await wait(300);const subprojectCreated=[...document.querySelectorAll('.list-main b')].some(x=>x.textContent==='界面子项目');row=document.querySelector('.list-row');row.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:250,clientY:300}));await wait(100);[...document.querySelectorAll('.context-menu button')].find(x=>x.textContent.includes('属性')).click();await wait(150);const propertiesVisible=!!document.querySelector('.properties-modal');document.querySelector('.modal-backdrop').dispatchEvent(new MouseEvent('click',{bubbles:true}));await wait(100);document.querySelector('.account-block').click();await wait(100);const accountMenuVisible=!!document.querySelector('.account-menu');[...document.querySelectorAll('.account-menu button')].find(x=>x.textContent.includes('设置')).click();await wait(200);return{subprojectDialogVisible,subprojectCreated,propertiesVisible,accountMenuVisible,settingsVisible:!!document.querySelector('.settings-modal'),workspacePath:document.querySelector('.path-box')?.textContent}})()`)
      Object.assign(result,uiResult)
      Object.assign(result,{archiveUiVisible:await win.webContents.executeJavaScript(`[...document.querySelectorAll('.settings-layout nav button')].some(button=>button.textContent.includes('归档'))`)})
      if(process.env.BEARAI_SMOKE_SETTINGS_SCREENSHOT)await writeFile(process.env.BEARAI_SMOKE_SETTINGS_SCREENSHOT,(await win.webContents.capturePage()).toPNG())
      const interactionMetrics=await win.webContents.executeJavaScript(`(()=>{const toggle=document.querySelector('.tree-toggle:not(.hidden)'),smart=document.querySelector('.smart-row'),account=document.querySelector('.account-block');return{treeToggle:toggle?{width:toggle.getBoundingClientRect().width,height:toggle.getBoundingClientRect().height,cursor:getComputedStyle(toggle).cursor}:null,smartCursor:getComputedStyle(smart).cursor,accountCursor:getComputedStyle(account).cursor}})()`)
      Object.assign(result,{interactionMetrics})
      const projectHeaderResult=await win.webContents.executeJavaScript(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));document.querySelector('.modal-actions button')?.click();[...document.querySelectorAll('.list-main')].at(-1)?.click();await wait(100);document.querySelector('.more')?.click();await wait(100);const themeButton=document.querySelector('.theme-swatches button[aria-label="林间"]');themeButton?.click();await wait(350);return{breadcrumbDepth:document.querySelectorAll('.breadcrumbs button').length,counts:document.querySelector('.status-stats')?.textContent,themeButtonFound:!!themeButton,shellClass:document.querySelector('.shell')?.className,projectThemeApplied:document.querySelector('.shell')?.classList.contains('theme-forest')}})()`)
      Object.assign(result,{projectHeaderResult})
      if(process.env.BEARAI_SMOKE_SCREENSHOT)await writeFile(process.env.BEARAI_SMOKE_SCREENSHOT,(await win.webContents.capturePage()).toPNG())
      if(process.env.BEARAI_SMOKE_PROJECT_SCREENSHOT){await win.webContents.executeJavaScript(`document.querySelector('.modal-actions button')?.click();[...document.querySelectorAll('.list-main')].at(-1)?.click()`);await new Promise(resolve=>setTimeout(resolve,250));await writeFile(process.env.BEARAI_SMOKE_PROJECT_SCREENSHOT,(await win.webContents.capturePage()).toPNG())}
      console.log(`BEARAI_SMOKE ${JSON.stringify(result)}`)
      const layoutPass=result.layoutResult.nav.height>700&&result.layoutResult.nav.bottom<=result.layoutResult.viewport.height&&result.layoutResult.list.width>900&&result.layoutResult.bodyScroll.height===result.layoutResult.viewport.height
      const interactionPass=result.interactionMetrics.treeToggle?.width>=32&&result.interactionMetrics.treeToggle?.height>=32&&result.interactionMetrics.treeToggle?.cursor==='pointer'&&result.interactionMetrics.smartCursor==='pointer'&&result.interactionMetrics.accountCursor==='pointer'
      const projectHeaderPass=result.projectHeaderResult.breadcrumbDepth>=2&&result.projectHeaderResult.counts?.includes('未完成')&&result.projectHeaderResult.counts?.includes('已完成')&&result.projectHeaderResult.counts?.includes('全部')&&result.projectHeaderResult.projectThemeApplied
      app.exit(result.projectPersisted&&result.childProjectPersisted&&result.taskPersisted&&result.childPersisted&&result.subprojectDialogVisible&&result.subprojectCreated&&result.propertiesVisible&&result.accountMenuVisible&&result.settingsVisible&&result.archiveUiVisible&&result.detailInitiallyHidden&&layoutPass&&interactionPass&&projectHeaderPass?0:1)
    } catch (error) { console.error('BEARAI_SMOKE_FAILED',error);app.exit(1) }
  })
}
app.whenReady().then(async () => {
  settingsRepository=new SettingsRepository(join(app.getPath('userData'),'settings.json'))
  const settings=await settingsRepository.read()
  configureRepositories(process.env.BEARAI_TODO_DATA_DIR??settings.workspacePath??join(app.getPath('userData'),'data'))
  await workspaceRepository.initialize();await projectRepository.initialize()
  ipcMain.handle('app:health', () => ({ ok:true, dataRoot }))
  ipcMain.handle('tasks:list', async () => {const tasks=await repository.list();await workspaceRepository.updateStatistics(tasks.filter(task=>task.status==='active').length,tasks.filter(task=>task.status==='completed').length);return tasks})
  ipcMain.handle('tasks:create', (_event, title:string, projectId:string, parentId:string|null) => repository.create(title,projectId,parentId))
  ipcMain.handle('tasks:save', async (_event, task, expectedRevision:number) => {const saved=await repository.save(task,expectedRevision);scheduleReminder(saved);return saved})
  ipcMain.handle('attachments:add',async (event,taskId:string)=>{const owner=BrowserWindow.fromWebContents(event.sender),result=owner?await dialog.showOpenDialog(owner,{title:'添加附件',properties:['openFile','multiSelections']}):await dialog.showOpenDialog({title:'添加附件',properties:['openFile','multiSelections']});if(result.canceled)return[];const folder=join(dataRoot,'.attachments',taskId);await mkdir(folder,{recursive:true});return Promise.all(result.filePaths.map(async source=>{const id=randomUUID(),name=basename(source),target=join(folder,`${id.slice(0,8)}--${name}`);await copyFile(source,target);const info=await stat(target);return{id,name,relativePath:relative(dataRoot,target).replace(/\\/g,'/'),mime:mimeTypes[extname(name).toLowerCase()]??'application/octet-stream',size:info.size,createdAt:new Date().toISOString()} satisfies TaskAttachment}))})
  ipcMain.handle('attachments:remove',async (_event,attachment:TaskAttachment)=>{await rm(attachmentPath(attachment.relativePath),{force:true});return true})
  ipcMain.handle('attachments:preview',async (_event,attachment:TaskAttachment)=>{const path=attachmentPath(attachment.relativePath),buffer=await readFile(path);if(buffer.length>25*1024*1024)return{supported:false,reason:'文件超过 25 MB，不支持内置预览'};const previewable=/^(image|audio|video)\//.test(attachment.mime)||attachment.mime==='application/pdf'||/^(text\/|application\/json)/.test(attachment.mime);if(!previewable)return{supported:false,reason:`暂不支持 ${attachment.mime} 格式的内置预览`};return{supported:true,mime:attachment.mime,dataUrl:`data:${attachment.mime};base64,${buffer.toString('base64')}`,text:/^(text\/|application\/json)/.test(attachment.mime)?buffer.toString('utf8'):undefined}})
  ipcMain.handle('attachments:download',async (event,attachment:TaskAttachment)=>{const owner=BrowserWindow.fromWebContents(event.sender),result=owner?await dialog.showSaveDialog(owner,{title:'保存附件',defaultPath:attachment.name}):await dialog.showSaveDialog({title:'保存附件',defaultPath:attachment.name});if(result.canceled||!result.filePath)return false;await copyFile(attachmentPath(attachment.relativePath),result.filePath);return true})
  ipcMain.handle('projects:list', () => projectRepository.initialize())
  ipcMain.handle('projects:list-archived', async () => Promise.all((await projectRepository.listArchived()).map(async project=>{const tasks=await new TaskRepository(join(dataRoot,project.relativePath)).list();return{project,active:tasks.filter(task=>task.status==='active').length,completed:tasks.filter(task=>task.status==='completed').length,total:tasks.length,tasks}})))
  ipcMain.handle('projects:create', (_event,name:string,parentId:string|null) => projectRepository.create(name,parentId))
  ipcMain.handle('projects:rename', (_event,projectId:string,name:string) => projectRepository.rename(projectId,name))
  ipcMain.handle('projects:update', (_event,projectId:string,patch) => projectRepository.update(projectId,patch))
  ipcMain.handle('projects:move', (_event,projectId:string,parentId:string|null) => projectRepository.move(projectId,parentId))
  ipcMain.handle('projects:archive', (_event,projectId:string) => projectRepository.archive(projectId))
  ipcMain.handle('settings:get', async () => ({...(await settingsRepository.read()),workspacePath:dataRoot}))
  ipcMain.handle('settings:set-theme', async (_event,theme) => ({...(await settingsRepository.setTheme(theme)),workspacePath:dataRoot}))
  ipcMain.handle('settings:set-preferences', async (_event,patch) => ({...(await settingsRepository.setPreferences(patch)),workspacePath:dataRoot}))
  ipcMain.handle('settings:choose-theme-background', async event => {const owner=BrowserWindow.fromWebContents(event.sender),options={title:'选择自定义主题背景',properties:['openFile'] as ('openFile')[],filters:[{name:'图片',extensions:['png','jpg','jpeg','webp','gif','svg']}]};const result=owner?await dialog.showOpenDialog(owner,options):await dialog.showOpenDialog(options);return result.canceled?null:result.filePaths[0]??null})
  ipcMain.handle('settings:change-workspace', async event => {const owner=BrowserWindow.fromWebContents(event.sender),options={title:'选择新的熊智ToDo工作目录',properties:['openDirectory','createDirectory'] as ('openDirectory'|'createDirectory')[],buttonLabel:'选择并迁移'};const result=owner?await dialog.showOpenDialog(owner,options):await dialog.showOpenDialog(options);if(result.canceled||!result.filePaths[0])return{canceled:true};const migration=await migrateWorkspace(dataRoot,result.filePaths[0]);await settingsRepository.setWorkspace(result.filePaths[0]);configureRepositories(result.filePaths[0]);await workspaceRepository.initialize();await projectRepository.initialize();return{canceled:false,migration,workspacePath:dataRoot}})
  ipcMain.on('window:minimize', event => BrowserWindow.fromWebContents(event.sender)?.minimize())
  ipcMain.on('window:toggle-maximize', event => { const win=BrowserWindow.fromWebContents(event.sender);if(win)win.isMaximized()?win.unmaximize():win.maximize() })
  ipcMain.on('window:close', event => BrowserWindow.fromWebContents(event.sender)?.close())
  for(const task of await repository.list())scheduleReminder(task)
  createWindow()
})
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit() })
