<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import type { Task, TaskStep } from './domain/task'
import type { ListGroup, TodoList } from './domain/list'
import { localDateKey, myDaySuggestions, queryTasks } from './domain/taskQueries'

const tasks=ref<Task[]>([]),lists=ref<TodoList[]>([]),groups=ref<ListGroup[]>([]),selected=ref<Task>()
const view=ref('inbox'),draft=ref(''),newListName=ref(''),newGroupName=ref(''),stepDraft=ref(''),search=ref(''),error=ref('')
const smart=[{id:'my-day',icon:'☀',name:'我的一天'},{id:'important',icon:'★',name:'重要'},{id:'planned',icon:'▣',name:'计划内'},{id:'all',icon:'∞',name:'全部'},{id:'completed',icon:'✓',name:'已完成'}]
const viewName=computed(()=>smart.find(item=>item.id===view.value)?.name??(view.value==='inbox'?'任务':lists.value.find(item=>item.id===view.value)?.name??'列表'))
const shown=computed(()=>{const result=queryTasks(tasks.value,view.value);const term=search.value.trim().toLocaleLowerCase();return term?result.filter(task=>[task.title,task.note,...task.tags,...task.steps.map(step=>step.title)].some(value=>value.toLocaleLowerCase().includes(term))):result})
const suggestions=computed(()=>myDaySuggestions(tasks.value).slice(0,5))
const ungrouped=computed(()=>lists.value.filter(item=>!item.groupId));const grouped=(id:string)=>lists.value.filter(item=>item.groupId===id)

function bridge(){if(!window.bearTodo)throw new Error('本地存储服务未连接，请重新启动应用');return window.bearTodo}
async function load(){try{const api=bridge();await api.health();[tasks.value,lists.value,groups.value]=await Promise.all([api.listTasks(),api.listLists(),api.listGroups()]);error.value=''}catch(reason){error.value=message(reason)}}
async function add(){const title=draft.value.trim();if(!title)return;try{const listId=lists.value.some(item=>item.id===view.value)?view.value:'inbox';const task=await bridge().createTask(title,listId);tasks.value.unshift(task);draft.value='';selected.value=task;error.value=''}catch(reason){error.value=message(reason)}}
async function save(task:Task,patch:Partial<Task>){error.value='';const original=task.revision;Object.assign(task,patch);try{Object.assign(task,await bridge().saveTask(task,original))}catch(reason){error.value=message(reason);await load()}}
async function toggleDone(task:Task){await save(task,{status:task.status==='completed'?'active':'completed',completedAt:task.status==='completed'?null:new Date().toISOString()})}
async function createList(groupId:string|null=null){const name=newListName.value.trim();if(!name)return;try{lists.value.push(await bridge().createList(name,groupId));newListName.value='';error.value=''}catch(reason){error.value=message(reason)}}
async function createListInGroup(groupId:string){const name=window.prompt('新列表名称')?.trim();if(name&&window.bearTodo)lists.value.push(await window.bearTodo.createList(name,groupId))}
async function createGroup(){const name=newGroupName.value.trim();if(!name)return;try{groups.value.push(await bridge().createGroup(name));newGroupName.value='';error.value=''}catch(reason){error.value=message(reason)}}
async function toggleGroup(item:ListGroup){if(!window.bearTodo)return;Object.assign(item,await window.bearTodo.saveGroup({...item,collapsed:!item.collapsed},item.revision))}
async function renameList(item:TodoList){const name=window.prompt('列表名称',item.name)?.trim();if(!name||!window.bearTodo)return;Object.assign(item,await window.bearTodo.saveList({...item,name},item.revision))}
async function archiveList(item:TodoList){if(!window.bearTodo||!window.confirm(`归档“${item.name}”？任务不会删除，可在恢复中心恢复列表。`))return;await window.bearTodo.archiveList(item);lists.value=lists.value.filter(value=>value.id!==item.id);if(view.value===item.id)view.value='inbox'}
async function renameGroup(item:ListGroup){const name=window.prompt('列表组名称',item.name)?.trim();if(!name||!window.bearTodo)return;Object.assign(item,await window.bearTodo.saveGroup({...item,name},item.revision))}
async function archiveGroup(item:ListGroup){if(!window.bearTodo||!window.confirm(`归档组“${item.name}”？组内列表不会被归档。`))return;await window.bearTodo.archiveGroup(item);groups.value=groups.value.filter(value=>value.id!==item.id);for(const list of lists.value.filter(value=>value.groupId===item.id)){Object.assign(list,await window.bearTodo.saveList({...list,groupId:null},list.revision))}}
async function moveGroup(item:ListGroup,direction:number){const peers=[...groups.value].sort((a,b)=>a.order-b.order);const index=peers.findIndex(value=>value.id===item.id),other=peers[index+direction];if(!other||!window.bearTodo)return;const order=item.order;Object.assign(item,await window.bearTodo.saveGroup({...item,order:other.order},item.revision));Object.assign(other,await window.bearTodo.saveGroup({...other,order},other.revision))}
async function moveList(item:TodoList,direction:number){const peers=lists.value.filter(value=>value.groupId===item.groupId).sort((a,b)=>a.order-b.order);const index=peers.findIndex(value=>value.id===item.id),other=peers[index+direction];if(!other||!window.bearTodo)return;const order=item.order;Object.assign(item,await window.bearTodo.saveList({...item,order:other.order},item.revision));Object.assign(other,await window.bearTodo.saveList({...other,order},other.revision))}
async function addStep(){if(!selected.value||!stepDraft.value.trim())return;const step:TaskStep={id:crypto.randomUUID(),title:stepDraft.value.trim(),completed:false};await save(selected.value,{steps:[...selected.value.steps,step]});stepDraft.value=''}
async function renameStep(step:TaskStep){if(!selected.value)return;const title=window.prompt('步骤名称',step.title)?.trim();if(title)await save(selected.value,{steps:selected.value.steps.map(value=>value.id===step.id?{...value,title}:value)})}
async function toggleStep(step:TaskStep){if(selected.value)await save(selected.value,{steps:selected.value.steps.map(value=>value.id===step.id?{...value,completed:!value.completed}:value)})}
async function removeStep(step:TaskStep){if(selected.value&&window.confirm(`删除步骤“${step.title}”？`))await save(selected.value,{steps:selected.value.steps.filter(value=>value.id!==step.id)})}
function message(reason:unknown){return reason instanceof Error?reason.message:'操作失败，请重新加载'}
onMounted(load)
</script>

<template><main class="shell" :class="{'has-detail':selected}"><header class="titlebar"><div class="drag-region"><span class="bear mini">熊</span><b>熊智ToDo</b></div><div class="window-controls"><button aria-label="最小化" @click="bridge().minimizeWindow()">—</button><button aria-label="最大化或还原" @click="bridge().toggleMaximizeWindow()">□</button><button class="close" aria-label="关闭" @click="bridge().closeWindow()">×</button></div></header>
  <aside class="nav" aria-label="列表导航"><div class="brand"><span class="bear">熊</span><strong>熊智ToDo</strong></div><label class="search"><span>⌕</span><input v-model="search" placeholder="搜索任务、标签或步骤" aria-label="全局搜索"/></label>
    <button v-for="item in smart" :key="item.id" :class="{selected:view===item.id}" @click="view=item.id"><span>{{item.icon}}</span>{{item.name}}<small>{{queryTasks(tasks,item.id).length}}</small></button><hr/>
    <button :class="{selected:view==='inbox'}" @click="view='inbox'"><span>☷</span>任务<small>{{queryTasks(tasks,'inbox').length}}</small></button>
    <section v-for="group in groups" :key="group.id" class="group"><header><button @click="toggleGroup(group)">{{group.collapsed?'›':'⌄'}} {{group.name}}</button><span><button title="组上移" @click="moveGroup(group,-1)">↑</button><button title="组下移" @click="moveGroup(group,1)">↓</button><button title="在组内新建列表" @click="createListInGroup(group.id)">＋</button><button title="改名" @click="renameGroup(group)">✎</button><button title="归档" @click="archiveGroup(group)">×</button></span></header><template v-if="!group.collapsed"><div v-for="item in grouped(group.id)" :key="item.id" class="list-row" :class="{selected:view===item.id}"><button class="list-main" @click="view=item.id"><span>☷</span><b>{{item.name}}</b></button><span class="actions"><button title="上移" @click="moveList(item,-1)">↑</button><button title="下移" @click="moveList(item,1)">↓</button><button title="改名" @click="renameList(item)">✎</button><button title="归档" @click="archiveList(item)">×</button></span></div></template></section>
    <div v-for="item in ungrouped" :key="item.id" class="list-row" :class="{selected:view===item.id}"><button class="list-main" @click="view=item.id"><span>☷</span><b>{{item.name}}</b></button><span class="actions"><button title="上移" @click="moveList(item,-1)">↑</button><button title="下移" @click="moveList(item,1)">↓</button><button title="改名" @click="renameList(item)">✎</button><button title="归档" @click="archiveList(item)">×</button></span></div>
    <div class="spacer"/><form class="new-row" @submit.prevent="createList(null)"><input v-model="newListName" placeholder="新建列表" aria-label="新列表名称"/><button aria-label="创建列表">＋</button></form><form class="new-row" @submit.prevent="createGroup"><input v-model="newGroupName" placeholder="新建列表组" aria-label="新列表组名称"/><button aria-label="创建列表组">⊞</button></form>
  </aside>
  <section class="list"><header><p>{{new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}}</p><h1>{{viewName}}</h1></header><p v-if="error" class="error" role="alert">{{error}}</p><div v-if="view!=='completed'" class="add"><span>＋</span><input v-model="draft" @keyup.enter="add" placeholder="添加任务" aria-label="任务标题"/></div><div v-if="view==='my-day'&&suggestions.length" class="suggestions"><b>建议</b><button v-for="task in suggestions" :key="task.id" @click="save(task,{myDay:localDateKey()})">＋ {{task.title}}</button></div>
    <div class="cards"><article v-for="task in shown" :key="task.id" @click="selected=task" :class="{active:selected?.id===task.id}"><button class="circle" :class="{done:task.status==='completed'}" :aria-label="task.status==='completed'?'恢复任务':'完成任务'" @click.stop="toggleDone(task)">{{task.status==='completed'?'✓':''}}</button><div><strong :class="{strike:task.status==='completed'}">{{task.title}}</strong><small>{{task.tags.map(tag=>'#'+tag).join(' ')||'任务'}}</small></div><button class="star" :aria-label="task.important?'取消重要':'标记重要'" @click.stop="save(task,{important:!task.important})">{{task.important?'★':'☆'}}</button></article><div v-if="!shown.length" class="empty"><b>{{search?'没有匹配结果':'这里还没有任务'}}</b><span>{{search?'尝试其他标题、标签或步骤关键词':'从添加一件小事开始'}}</span></div></div>
  </section>
  <aside v-if="selected" class="detail" aria-label="任务详情"><div class="task-title"><button class="circle" :class="{done:selected.status==='completed'}" @click="toggleDone(selected)">{{selected.status==='completed'?'✓':''}}</button><input v-model="selected.title" @change="save(selected,{title:selected.title})" aria-label="任务标题"/><button class="star" @click="save(selected,{important:!selected.important})">{{selected.important?'★':'☆'}}</button></div>
    <div class="steps"><div v-for="step in selected.steps" :key="step.id"><button class="circle" :class="{done:step.completed}" @click="toggleStep(step)">{{step.completed?'✓':''}}</button><button class="step-name" :class="{strike:step.completed}" @dblclick="renameStep(step)">{{step.title}}</button><button title="删除步骤" @click="removeStep(step)">×</button></div><form @submit.prevent="addStep"><input v-model="stepDraft" placeholder="添加步骤" aria-label="步骤名称"/><button>＋</button></form></div>
    <button @click="save(selected,{myDay:selected.myDay===localDateKey()?null:localDateKey()})">☀ {{selected.myDay===localDateKey()?'从“我的一天”移除':'加入“我的一天”'}}</button><button disabled title="下一批实现">◷ 提醒我</button><button disabled title="下一批实现">▣ 添加截止日期</button><button disabled title="下一批实现">↻ 重复</button><textarea v-model="selected.note" @change="save(selected,{note:selected.note})" placeholder="添加备注"></textarea><small>创建于 {{new Date(selected.createdAt).toLocaleDateString()}}</small></aside>
</main></template>
