<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import type { Task } from './domain/task'
import type { Project } from './domain/project'
import { childTasks, queryTasks } from './domain/taskQueries'

const tasks=ref<Task[]>([]),projects=ref<Project[]>([]),selected=ref<Task>()
const view=ref('today'),draft=ref(''),newProjectName=ref(''),childDraft=ref(''),search=ref(''),error=ref('')
const menu=ref<{project:Project;x:number;y:number}|null>(null)
const smart=[{id:'today',icon:'☀',name:'今日待办'},{id:'favorites',icon:'★',name:'收藏'},{id:'planned',icon:'▣',name:'计划内'},{id:'completed',icon:'✓',name:'已完成'}]
const projectRows=computed(()=>{const result:{project:Project;depth:number}[]=[];const visit=(parentId:string|null,depth:number)=>projects.value.filter(item=>item.parentId===parentId).sort((a,b)=>a.order-b.order).forEach(project=>{result.push({project,depth});visit(project.projectId,depth+1)});visit(null,0);return result})
const viewName=computed(()=>smart.find(item=>item.id===view.value)?.name??projects.value.find(item=>item.projectId===view.value)?.name??'今日待办')
const shown=computed(()=>{const result=queryTasks(tasks.value,view.value);const term=search.value.trim().toLocaleLowerCase();return term?result.filter(task=>[task.title,task.note,...task.tags,...childTasks(tasks.value,task.id).map(child=>child.title)].some(value=>value.toLocaleLowerCase().includes(term))):result})
const children=computed(()=>selected.value?childTasks(tasks.value,selected.value.id):[])
function bridge(){if(!window.bearTodo)throw new Error('本地存储服务未连接，请重新启动应用');return window.bearTodo}
async function load(){try{const api=bridge();await api.health();[tasks.value,projects.value]=await Promise.all([api.listTasks(),api.listProjects()]);error.value=''}catch(reason){error.value=message(reason)}}
function defaultProject(){return projects.value.find(item=>item.name==='任务'&&item.parentId===null)??projects.value[0]}
async function add(){const title=draft.value.trim(),project=projects.value.find(item=>item.projectId===view.value)??defaultProject();if(!title||!project)return;try{const task=await bridge().createTask(title,project.projectId);tasks.value.unshift(task);draft.value='';selected.value=task;error.value=''}catch(reason){error.value=message(reason)}}
async function save(task:Task,patch:Partial<Task>){const original=task.revision;Object.assign(task,patch);try{Object.assign(task,await bridge().saveTask(task,original));error.value=''}catch(reason){error.value=message(reason);await load()}}
async function toggleDone(task:Task){await save(task,{status:task.status==='completed'?'active':'completed',completedAt:task.status==='completed'?null:new Date().toISOString()})}
async function addChildTask(){const parent=selected.value,title=childDraft.value.trim();if(!parent||!title)return;try{tasks.value.push(await bridge().createTask(title,parent.projectId,parent.id));childDraft.value=''}catch(reason){error.value=message(reason)}}
async function renameChild(child:Task){const title=window.prompt('子任务名称',child.title)?.trim();if(title)await save(child,{title})}
async function createProject(parentId:string|null=null,name?:string){const value=(name??newProjectName.value).trim();if(!value)return;try{projects.value.push(await bridge().createProject(value,parentId));newProjectName.value='';menu.value=null;error.value=''}catch(reason){error.value=message(reason)}}
function openMenu(event:MouseEvent,project:Project){event.preventDefault();menu.value={project,x:event.clientX,y:event.clientY}}
async function addSubproject(project:Project){const name=window.prompt(`在“${project.name}”中新增子项目`)?.trim();if(name)await createProject(project.projectId,name)}
async function renameProject(project:Project){const name=window.prompt('项目名称',project.name)?.trim();if(!name)return;try{const saved=await bridge().renameProject(project.projectId,name);Object.assign(project,saved);menu.value=null}catch(reason){error.value=message(reason)}}
async function archiveProject(project:Project){if(!window.confirm(`归档项目“${project.name}”及其目录内容？可从工作目录的 .archive 中恢复。`))return;try{await bridge().archiveProject(project.projectId);const archivedIds=new Set([project.projectId]);let changed=true;while(changed){changed=false;for(const item of projects.value)if(item.parentId&&archivedIds.has(item.parentId)&&!archivedIds.has(item.projectId)){archivedIds.add(item.projectId);changed=true}}projects.value=projects.value.filter(item=>!archivedIds.has(item.projectId));if(archivedIds.has(view.value))view.value='today';menu.value=null}catch(reason){error.value=message(reason)}}
function message(reason:unknown){return reason instanceof Error?reason.message:'操作失败，请重新加载'}
onMounted(load)
</script>

<template><main class="shell" :class="{'has-detail':selected}" @click="menu=null"><header class="titlebar"><div class="drag-region"><span class="bear mini">熊</span><b>熊智ToDo</b></div><div class="window-controls"><button aria-label="最小化" @click="bridge().minimizeWindow()">—</button><button aria-label="最大化或还原" @click="bridge().toggleMaximizeWindow()">□</button><button class="close" aria-label="关闭" @click="bridge().closeWindow()">×</button></div></header>
  <aside class="nav" aria-label="任务与项目导航"><label class="search"><span>⌕</span><input v-model="search" placeholder="搜索任务、标签或子任务" aria-label="全局搜索"/></label><button v-for="item in smart" :key="item.id" :class="{selected:view===item.id}" @click="view=item.id"><span>{{item.icon}}</span>{{item.name}}<small>{{queryTasks(tasks,item.id).length}}</small></button><hr/><div class="section-title">项目</div><div v-for="row in projectRows" :key="row.project.projectId" class="list-row" :class="{selected:view===row.project.projectId}" :style="{'--depth':row.depth}" @contextmenu="openMenu($event,row.project)"><button class="list-main" @click="view=row.project.projectId"><span>{{row.depth?'└':'▰'}}</span><b>{{row.project.name}}</b><small>{{queryTasks(tasks,row.project.projectId).length}}</small></button></div><div class="spacer"/><form class="new-row" @submit.prevent="createProject(null)"><input v-model="newProjectName" placeholder="新建项目" aria-label="新项目名称"/><button aria-label="创建项目">＋</button></form></aside>
  <section class="list"><header><p>{{new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}}</p><h1>{{viewName}}</h1></header><p v-if="error" class="error" role="alert">{{error}}</p><div v-if="view!=='completed'" class="add"><span>＋</span><input v-model="draft" @keyup.enter="add" placeholder="添加任务" aria-label="任务标题"/></div><div class="cards"><article v-for="task in shown" :key="task.id" @click="selected=task" :class="{active:selected?.id===task.id}"><button class="circle" :class="{done:task.status==='completed'}" :aria-label="task.status==='completed'?'恢复任务':'完成任务'" @click.stop="toggleDone(task)">{{task.status==='completed'?'✓':''}}</button><div><strong :class="{strike:task.status==='completed'}">{{task.title}}</strong><small>{{task.tags.map(tag=>'#'+tag).join(' ')||projects.find(project=>project.projectId===task.projectId)?.name||'任务'}}</small></div><button class="star" :aria-label="task.favorite?'取消收藏':'收藏任务'" @click.stop="save(task,{favorite:!task.favorite})">{{task.favorite?'★':'☆'}}</button></article><div v-if="!shown.length" class="empty"><b>{{search?'没有匹配结果':'这里还没有任务'}}</b><span>{{search?'尝试其他关键词':'从添加一件小事开始'}}</span></div></div></section>
  <aside v-if="selected" class="detail" aria-label="任务详情"><div class="task-title"><button class="circle" :class="{done:selected.status==='completed'}" @click="toggleDone(selected)">{{selected.status==='completed'?'✓':''}}</button><input v-model="selected.title" @change="save(selected,{title:selected.title})" aria-label="任务标题"/><button class="star" :aria-label="selected.favorite?'取消收藏':'收藏任务'" @click="save(selected,{favorite:!selected.favorite})">{{selected.favorite?'★':'☆'}}</button></div><div class="steps" aria-label="子任务"><div v-for="child in children" :key="child.id"><button class="circle" :class="{done:child.status==='completed'}" @click="toggleDone(child)">{{child.status==='completed'?'✓':''}}</button><button class="step-name" :class="{strike:child.status==='completed'}" @dblclick="renameChild(child)">{{child.title}}</button><button class="star" @click="save(child,{favorite:!child.favorite})">{{child.favorite?'★':'☆'}}</button></div><form @submit.prevent="addChildTask"><input v-model="childDraft" placeholder="添加子任务" aria-label="子任务名称"/><button>＋</button></form></div><button disabled>◷ 提醒我</button><button disabled>▣ 添加截止日期</button><button disabled>↻ 重复</button><textarea v-model="selected.note" @change="save(selected,{note:selected.note})" placeholder="添加备注"></textarea><small>创建于 {{new Date(selected.createdAt).toLocaleDateString()}}</small></aside>
  <div v-if="menu" class="context-menu" :style="{left:menu.x+'px',top:menu.y+'px'}" @click.stop><button @click="addSubproject(menu.project)">新增子项目</button><button @click="renameProject(menu.project)">重命名</button><button class="danger" @click="archiveProject(menu.project)">归档</button></div>
</main></template>
