import type { Task, TaskAttachment } from './domain/task'
import type { Project, ProjectTheme, ProjectViewSettings } from './domain/project'
import type { CustomTheme } from './domain/theme'
declare global { interface Window { bearTodo?: {
  health():Promise<{ok:boolean;dataRoot:string}>
  listTasks():Promise<Task[]>; createTask(title:string,projectId:string,parentId?:string|null):Promise<Task>; saveTask(task:Task,expectedRevision:number):Promise<Task>; completeTask(taskId:string,expectedRevision:number):Promise<{completed:Task;next:Task|null}>;voidTask(taskId:string,expectedRevision:number,reason?:string):Promise<{voided:Task;next:Task|null}>;restoreVoidedTask(taskId:string,expectedRevision:number):Promise<Task>;findTaskInstance(instanceKey:string):Promise<Task|null>;ensureTaskInstance(request:import('./domain/task').EnsureTaskInstanceDto):Promise<{task:Task;created:boolean}>;voidExpiredTaskInstances(today:string,reason?:string):Promise<Task[]>;placeTask(placement:import('./domain/task').TaskPlacementDto):Promise<Task>
  addAttachments(taskId:string):Promise<TaskAttachment[]>;importEditorImage(taskId:string,name:string,mime:string,bytes:ArrayBuffer):Promise<TaskAttachment>;readClipboardImage():Promise<{name:string;mime:string;bytes:number[]}|null>;removeAttachment(attachment:TaskAttachment):Promise<boolean>;previewAttachment(attachment:TaskAttachment):Promise<{supported:boolean;reason?:string;mime?:string;dataUrl?:string;text?:string}>;downloadAttachment(attachment:TaskAttachment):Promise<boolean>
  listProjects():Promise<Project[]>;listArchivedProjects():Promise<{project:Project;active:number;completed:number;total:number;tasks:Task[]}[]>;createProject(name:string,parentId?:string|null):Promise<Project>;renameProject(projectId:string,name:string):Promise<Project>;updateProject(projectId:string,patch:Partial<Pick<Project,'name'|'icon'|'description'|'sidebarColor'|'theme'|'collapsed'|'viewSettings'|'settingsMode'|'git'>>):Promise<Project>;openProjectFolder(projectId:string):Promise<string>;moveProject(projectId:string,parentId:string|null):Promise<Project>;reorderProject(placement:import('./domain/project').ProjectReorderDto):Promise<Project>;moveProjectChecked(placement:import('./domain/project').ProjectMoveDto):Promise<Project>;archiveProject(projectId:string,expectedRevision?:number):Promise<Project>
  getSettings():Promise<{workspacePath:string|null;theme:ProjectTheme;sidebarWidth:number;customTheme:{accent:string;scene:string;backgroundImage:string|null};customThemes:CustomTheme[];todayWindowDays:number;projectDefaults:ProjectViewSettings;currentUser?:import('./domain/task').UserIdentity}>;setTheme(theme:ProjectTheme):Promise<{workspacePath:string|null;theme:ProjectTheme}>;setPreferences(patch:{theme?:ProjectTheme;sidebarWidth?:number;customTheme?:{accent:string;scene:string;backgroundImage:string|null};customThemes?:CustomTheme[];todayWindowDays?:number;projectDefaults?:Partial<ProjectViewSettings>;currentUser?:import('./domain/task').UserIdentity}):Promise<{workspacePath:string|null;theme:ProjectTheme;sidebarWidth:number;customTheme:{accent:string;scene:string;backgroundImage:string|null};customThemes:CustomTheme[];todayWindowDays:number;projectDefaults:ProjectViewSettings;currentUser?:import('./domain/task').UserIdentity}> ;chooseThemeBackground(themeId:string):Promise<string|null>;changeWorkspace():Promise<{canceled:boolean;workspacePath?:string;migration?:{projects:number;tasks:number;source:string;target:string;sourceRemoved:boolean}}>
  listWorkspaces():Promise<import('./infrastructure/workspaceRegistryRepository').WorkspaceRegistry>;switchWorkspace(workspaceId:string):Promise<import('./infrastructure/workspaceRegistryRepository').WorkspaceRegistry>;addWorkspace():Promise<{canceled:boolean;registry?:import('./infrastructure/workspaceRegistryRepository').WorkspaceRegistry}>;createWorkspace(name:string):Promise<{canceled:boolean;registry?:import('./infrastructure/workspaceRegistryRepository').WorkspaceRegistry}>;renameWorkspace(workspaceId:string,name:string):Promise<import('./infrastructure/workspaceRegistryRepository').WorkspaceRegistry>;removeWorkspace(workspaceId:string):Promise<import('./infrastructure/workspaceRegistryRepository').WorkspaceRegistry>;openWorkspace(workspaceId:string):Promise<string>
  minimizeWindow():void; toggleMaximizeWindow():void; closeWindow():void
} } }
export {}
