import type { Task, TaskAttachment } from './domain/task'
import type { Project, ProjectTheme, ProjectViewSettings } from './domain/project'
declare global { interface Window { bearTodo?: {
  health():Promise<{ok:boolean;dataRoot:string}>
  listTasks():Promise<Task[]>; createTask(title:string,projectId:string,parentId?:string|null):Promise<Task>; saveTask(task:Task,expectedRevision:number):Promise<Task>
  addAttachments(taskId:string):Promise<TaskAttachment[]>;removeAttachment(attachment:TaskAttachment):Promise<boolean>;previewAttachment(attachment:TaskAttachment):Promise<{supported:boolean;reason?:string;mime?:string;dataUrl?:string;text?:string}>;downloadAttachment(attachment:TaskAttachment):Promise<boolean>
  listProjects():Promise<Project[]>;listArchivedProjects():Promise<{project:Project;active:number;completed:number;total:number;tasks:Task[]}[]>;createProject(name:string,parentId?:string|null):Promise<Project>;renameProject(projectId:string,name:string):Promise<Project>;updateProject(projectId:string,patch:Partial<Pick<Project,'name'|'icon'|'description'|'sidebarColor'|'theme'|'collapsed'|'viewSettings'|'settingsMode'>>):Promise<Project>;moveProject(projectId:string,parentId:string|null):Promise<Project>;archiveProject(projectId:string):Promise<Project>
  getSettings():Promise<{workspacePath:string|null;theme:ProjectTheme;sidebarWidth:number;customTheme:{accent:string;scene:string;backgroundImage:string|null};projectDefaults:ProjectViewSettings}>;setTheme(theme:ProjectTheme):Promise<{workspacePath:string|null;theme:ProjectTheme}>;setPreferences(patch:{theme?:ProjectTheme;sidebarWidth?:number;customTheme?:{accent:string;scene:string;backgroundImage:string|null};projectDefaults?:Partial<ProjectViewSettings>}):Promise<{workspacePath:string|null;theme:ProjectTheme;sidebarWidth:number;customTheme:{accent:string;scene:string;backgroundImage:string|null};projectDefaults:ProjectViewSettings}> ;chooseThemeBackground():Promise<string|null>;changeWorkspace():Promise<{canceled:boolean;workspacePath?:string;migration?:{projects:number;tasks:number;source:string;target:string;sourceRemoved:boolean}}>
  minimizeWindow():void; toggleMaximizeWindow():void; closeWindow():void
} } }
export {}
